// <auto-generated />
using System;
using Code_Academy_Space_Booking_System.MyDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code_Academy_Space_Booking_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231217084044_add data")]
    partial class adddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Code_Academy_Space_Booking_System.Models.Booking", b =>
                {
                    b.Property<int>("BookingNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingNo"), 1L, 1);

                    b.Property<DateTime>("B_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingNo");

                    b.HasIndex("CId");

                    b.HasIndex("SId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System.Models.Client", b =>
                {
                    b.Property<int>("C_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("C_id"), 1L, 1);

                    b.Property<string>("C_DOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("C_Phone")
                        .HasColumnType("int");

                    b.Property<string>("C_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("C_id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System.Models.Space", b =>
                {
                    b.Property<int>("S_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("S_id"), 1L, 1);

                    b.Property<string>("S_Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("availability_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("S_id");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System.Models.Booking", b =>
                {
                    b.HasOne("Code_Academy_Space_Booking_System.Models.Client", "Clients")
                        .WithMany("ClientBooking")
                        .HasForeignKey("CId");

                    b.HasOne("Code_Academy_Space_Booking_System.Models.Space", "Spaces")
                        .WithMany("SpaceBooking")
                        .HasForeignKey("SId");

                    b.Navigation("Clients");

                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System.Models.Client", b =>
                {
                    b.Navigation("ClientBooking");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System.Models.Space", b =>
                {
                    b.Navigation("SpaceBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
